config/routes.rb
Readathon2::Application.routes.draw do
  root 'pages#index'
  resources :students
  resources :teachers, only: [:index, :new, :show]
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :name
  
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  validates_presence_of :name
  has_many :students
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
  
  def new
    @student = Student.new
  end  
  
  def create
    @student = Student.new student_params
    
    if @student.save
      flash[:notice] = "Student Successfully Created."
      
      redirect_to @student
    else
      render "new"
    end
  end
  
  def show
    @student = Student.find params[:id]
  end
  
  def edit
    @student = Student.find params[:id]
  end
  
  def update
    @student = Student.find params[:id]
    if @student.update_attributes student_params
      flash[:notice] = "Student Successfully Updated."
      redirect_to @student
    else
      render "edit"
    end
  end
  
  def destroy
    @student = Student.find params[:id]
    
    if @student.destroy
      flash[:notice] = "Student Successfully Destroyed."
      redirect_to students_path
    else
      render @student
    end
  end
  
  private
  
  def student_params
    params.require(:student).permit(:name, :teacher_id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end
  
  def new
    @student = Student.new
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readathon2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  
  <div class="container">
  
    <div class="login">
        <% if signed_in? %>                                                                                                                 
      Welcome <%= current_user.email %>                                                                                           
      <%= link_to 'Sign out', sign_out_path, :method => :delete %>                                                                      
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>   
      <br />
      <%= link_to 'Sign up', sign_up_path %>   
    <% end %>                                                                                                                           
                                                                                                                                        
    <div id="flash">                                                                                                                    
      <% flash.each do |key, value| %>                                                                                                  
        <div class="flash <%= key %>"><%= value %></div>                                                                                
      <% end %>                                                                                                                         
    </div>  
      
    </div>
    
    
    <%= render "shared/flash" %>
    
    <%= yield %>
  </div>
  
</body>
</html>

app/views/pages/index.html.erb
<h1> Welcome to the Readathon2 web app</h1>

  <%= link_to "Students", students_path %>
  <%= link_to "Teachers", teachers_path %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "flash #{name}" %>
<% end %>

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <%= f.input :name %>
  <%= f.input :teacher_id, collection: Teacher.all %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<%= render partial: "form" %>

app/views/students/index.html.erb
<h1> Students</h1>
<%= link_to "Add Student", new_student_path %>
<br /><br />

<% @students.each do |student| %>
    <div class="student">
     <%= link_to student.name, student %>
     </div>
<% end %>

app/views/students/new.html.erb
<%= render partial: "form" %>

app/views/students/show.html.erb
<%= link_to "Back to student list", students_path %>

<h1><%= @student.name %></h1>
<h2><%= @student.teacher.name %></h2>

<%= link_to "Edit", edit_student_path %>
<%= link_to "Delete", @student, method: :delete, data:{confirm: "Are you sure?"} %>

app/views/teachers/index.html.erb
<h1> Teachers</h1>
<%= link_to "Add Teacher", new_teacher_path %>
<br /><br />

<% @teachers.each do |teacher| %>
    <div class="teacher">
      <%= link_to teacher.name, teacher %>
     </div>
<% end %>